#!/bin/bash
# Color and formatting utilities
# Generated by UtilityFunctionsSetup

set -euo pipefail

# Check if colors are supported
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1; then
    # Colors are supported
    RED="\033[0;31m"
    GREEN="\033[0;32m"
    YELLOW="\033[1;33m"
    BLUE="\033[0;34m"
    PURPLE="\033[0;35m"
    CYAN="\033[0;36m"
    WHITE="\033[1;37m"
    BOLD="\033[1m"
    DIM="\033[2m"
    NC="\033[0m" # No Color
else
    # Colors are not supported
    RED=""
    GREEN=""
    YELLOW=""
    BLUE=""
    PURPLE=""
    CYAN=""
    WHITE=""
    BOLD=""
    DIM=""
    NC=""
fi

# Print colored text
print_red() {
    echo -e "${RED}$*${NC}"
}

print_green() {
    echo -e "${GREEN}$*${NC}"
}

print_yellow() {
    echo -e "${YELLOW}$*${NC}"
}

print_blue() {
    echo -e "${BLUE}$*${NC}"
}

print_purple() {
    echo -e "${PURPLE}$*${NC}"
}

print_cyan() {
    echo -e "${CYAN}$*${NC}"
}

print_white() {
    echo -e "${WHITE}$*${NC}"
}

print_bold() {
    echo -e "${BOLD}$*${NC}"
}

print_dim() {
    echo -e "${DIM}$*${NC}"
}

# Print success message
print_success() {
    print_green "✅ $*"
}

# Print error message
print_error() {
    print_red "❌ $*"
}

# Print warning message
print_warning() {
    print_yellow "⚠️  $*"
}

# Print info message
print_info() {
    print_blue "ℹ️  $*"
}

# Print header
print_header() {
    echo
    print_bold "${BLUE}=== $* ===${NC}"
    echo
}

# Print separator
print_separator() {
    echo -e "${DIM}$(printf "=%.0s" {1..80})${NC}"
}

echo "Color utilities loaded successfully"